vim.keymap.set("n", "<leader>at", function()
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_open_win(buf, true, { split = "below", height = 15 })
  vim.fn.termopen("opencode", { cwd = vim.fn.getcwd() })
end, { desc = "toggle opencode terminal" })
